services:

  postgres:
    image: postgres:17
    container_name: assessment-postgres
    environment:
      POSTGRES_DB: assessment
      POSTGRES_USER: assessment
      POSTGRES_PASSWORD: assessment
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: assessment-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data: